### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by PystoyPlayer** [alt-art/TelegramBridge#11]
Nice. But now can you add MarkdownV2 support pls ? And link preview hider
![Shot (2024-03-24 at 04 22PM)@2x](https://github.com/alt-art/TelegramBridge/assets/88878911/590222ff-ad6e-4e72-bd33-8d0775a49dc6)

**Comment by PystoyPlayer** [comment]
Should be
![Shot (2024-03-24 at 04 24PM)@2x](https://github.com/alt-art/TelegramBridge/assets/88878911/d42785d4-9de7-4420-852a-4c5b510ec15a)

**Comment by alt-art** [comment]
You can use HTML, markdown on telegram is a bit odd because they check syntaxes

**Comment by alt-art** [comment]
HTML makes it easier to correct syntax errors than Telegram Markdown.

**Comment by PystoyPlayer** [comment]
Ah, HTML, thanks. But what about link previews ?

**Comment by alt-art** [comment]
You can use `<a href="(link)">(label)</a>` and will work fine

This is what looks like:

![Screenshot from 2024-03-24 21-50-48](https://github.com/alt-art/TelegramBridge/assets/43281034/47fdf0fc-9a1f-48b1-9d65-7900a8fe5282)

**Comment by alt-art** [comment]
Hmm I don't know if I can solve this, I will do some tests.

**Comment by PystoyPlayer** [comment]
I think you need to set link_preview_options
https://core.telegram.org/bots/api#sendmessage

**Comment by alt-art** [comment]
Thank you, I will do some refactoring and will make this change

**Comment by alt-art** [comment]
Sorry for delay making version 1.2.2 now
