### ISSUE TITLE
Send console messages to another thread

### ISSUE THREAD

**Issue by orzklv** [alt-art/TelegramBridge#22]
It would be beneficial to send server console messages to another thread and bridge messages from that thread to console if the sender is registered as admin or is admin|owner of that chat.

**Comment by mmnvb** [comment]
yep yep

**Comment by alt-art** [comment]
I will add a big update with things related to this PR.

I'm working on a full-time job and that is why I am less active in this project, don't expect too much.

**Comment by orzklv** [comment]
@alt-art  No worries bro, open source is a voluntary work. You could have said "do it yourself" and yet didn't. I do apologize if it felt rude or mean. I do appreciate your work.

**Comment by alt-art** [comment]
> You could have said "do it yourself" and yet didn't.

I was thinking if this pull request would be beneficial compared with things that I will have to add that makes it more difficult for those who don't want this configuration.

The most important thing is that this project is personal for my own use and I only add things that I know my server needs or that will help a large portion of the users.

Putting all this together with the fact that I was working on another project and didn't want to think too much about what to do with this PR.

No need to feel bad, I really needed to have said this earlier and discussed this PR more, and I appreciate that you understand and know that open-source projects are made by people who just wants to do something fun.
